name: Robot Framework Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Robot Framework
        run: |
          pip install robotframework

      - name: Run Robot Framework tests
        run: |
          mkdir results
          robot --outputdir results test_calculator.robot

      - name: Upload Robot Framework results
        uses: actions/upload-artifact@v3
        with:
          name: robot-test-results
          path: results/
